### PR TITLE
Expand readme

### PR DESCRIPTION
**Pull request by mfherbst**

### CODE REVIEW

**Review by pseyfert — DISMISSED** [review]
I approve this PR.

I made some changes:
 - long links at the end of the file
 - add license badge

**Review by pseyfert — DISMISSED** [review]
okay, apparently rebasing requires a new review.

I approve this PR

I made small changes wrt @mfherbst's version:
 - put long links to bottom of readme
 - add licence badge

**Comment by pseyfert** [comment]
@mfherbst, check if you like my changes.

**Comment by mfherbst** [comment]
Agree, expept that I'd prefer using the shields.io which uses the github api for getting the licence.

**Review by pseyfert — APPROVED** [review]

**Pull request merged**
