### PR TITLE
Feature/fulltext output dir config

### LINKED ISSUE #29: Add configuration options for download directory
It would be nice to make the directory where downloads are stored configurable.

### PR DESCRIPTION
**Pull request by mfherbst**
Command line and configuration via `config.yaml` for the output directory of the `get_fulltext.py` path.

Resolves #29.

### CODE REVIEW

**Comment by andrenarchy** [comment]
One question: do we actually need it as a command line option or isn't this more sth that you only configure once?

**Comment by mfherbst** [comment]
Not sure about that. I guess sometimes you might want to try or test something and having a command line flag could be useful. But then you might have a totally different configuration for that anyways, hence no need to have the command line flag.

I think it does not hurt much to have it for flexibility, but if we find out that we start to add to many command line arguments, we might be better off to remove it.

**Comment by andrenarchy** [comment]
Yeah, I agree. I guess the question is if we want to expose all/most of the options from the config file in the CLI as well. Personally, I tend to only include things if someone actually needs it – so if you have an actual use case then that's fine. :)

**Review by andrenarchy — CHANGES_REQUESTED** [review]
Can you also update the README?

**Comment by andrenarchy** [comment]
Oh, and this PR also contains the commit from #31.

**Comment by mfherbst** [comment]
- Removed the commit from #31. My bad.
- Added documentation for configuration file in separate file in `doc` subdirectory.

**Review by andrenarchy — APPROVED** [review]

**Pull request merged**
